User File
WildCodeSchool/daily-shuffler-toulouse pull request #6
Opened 2020-11-02 16:42 UTC by sebastienbages

- Student.txt added _(DailyShufflerToulouse\bin\Debug\netcoreapp3.1\)_
- Program.cs modified : method added to read the file and add the names of the array string "tableauStudents" (! one name per line!)

Remaining at your disposal

2020-11-05 08:11 UTC, prevostcorentin requested changes

2020-11-05 08:11 UTC, prevostcorentin commented on DailyShufflerToulouse/Program.cs
> +            String[] toulouseStudents = System.IO.File.ReadAllLines(@".\Students.txt"); // IMPORTANT ! : Please note one name per line
`ReadAllLines` lit toutes les lignes d'un fichier et les stocke dans un tableau.

Que se passe t-il si mon fichier fait 2G ?

Ce n'est pas le cas, mais notre programme ainsi que le fichier contenant les étudiants va évoluer.

Ne lit pas du tout d'un coup, mais ligne par ligne. Ne stocke pas tout le fichier en mémoire vive, la mémoire morte sert à ça ;)

2020-11-05 17:00 UTC, sebastienbages commented on DailyShufflerToulouse/Program.cs
> +            String[] toulouseStudents = System.IO.File.ReadAllLines(@".\Students.txt"); // IMPORTANT ! : Please note one name per line
J'ai modifié la méthode selon les références que tu m'as transmis.

Merci pour tes remarques.

2020-11-09 08:37 UTC, prevostcorentin approved these changes

2020-11-09 08:38 UTC, merged